### ISSUE TITLE
Console sessions no longer shown in 'running'

### ISSUE THREAD

**Issue by svenefftinge** [jupyter/jupyterlab#1048]
With the latest master the console sessions are no longer shown in the 'running' widget.

**Comment by blink1073** [comment]
Hi @svenefftinge, we explicitly do not show console sessions yet because they are an oddball.  The only thing distinguishing them right now from a file-backed session is that they do not have a file extension.  However, we are looking to improve this situation by allowing server-side session objects to have a `name` and a `type`: https://github.com/jupyter/jupyter-js-services/pull/237

**Comment by svenefftinge** [comment]
ok, thanks.
