### ISSUE TITLE
Merged cell in reversed order

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#302]
When selecting multiple cells down and merging, cell get merged in reversed order. 

- Create 3 cell 1 to 3. 
- Select first cell. 
- Shift-Down 2 times while in command mode. 
- Merge (Shift-M) 

Expected:

Cell 1 - contain 1, 2, 3

Observed

Cell 1 contain 3,2,1

This does not happen when selecting down-up.

**Comment by willingc** [comment]
Confirming same behavior seen as @Carreau. Here's a gist with a test notebook: https://gist.github.com/willingc/9ea18c8126e7dc4349433ef319058eb2

**Comment by jasongrout** [comment]
Huh, I get 3, 1, 2. But still, definitely not the right order.

**Comment by F-A** [comment]
Somehow this also depends on the selection order. If you select the 3rd cells and extend the selction upwards to the 1st cell, then the cells are merged in the right order...

**Comment by blink1073** [comment]
Help is welcome, @F-A!  The relevant code is here: https://github.com/jupyter/jupyterlab/blob/master/src/notebook/notebook/actions.ts#L102

**Comment by F-A** [comment]
@blink1073 Sorry, I currently have too much work and I won't have time to fix it any time soon.

However, having a quick look at the code using firefox debugger, the problem comes from the "active cell":
- you first create a list of cells to merge, excluding the currently active one (in case of a up to bottom selection, the last bottom one)
- you then clone the active cell (l. 139)  and append to it the code of the cells to merge
As a result your new cells code is: the active cell code (the last one) followed by the other selected cells in the right order.

I do not really understand why one use the last selected cell as primary. I would rather use the first selected cell, i.e. the top one) which should solve the bug.

**Comment by blink1073** [comment]
No worries, thank you for taking a crack at it.
