### ISSUE TITLE
Restore autosave ?

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyterlab#335]
The fact the jupyterlab does have the ability to prevent closing phosphor tabs and save notebook is great, though other things can happen like network connection down... etc, and a few time I've close JupyterLab withhout saving, with habit of normal notebook. 

Can we re-enable, or speedup the delay between autosave?

**Comment by blink1073** [comment]
Spit-balling:  We should create checkpoints for all documents from the context manager whenever we save, and have it create checkpoints for all open files periodically.  When we load a file, check for a checkpoint before getting the disk contents.

**Comment by blink1073** [comment]
Okay, I had misinterpreted what a checkpoint is.  They were created only when created explicitly saving.  The *file itself* is auto-saved (but only notebooks previously).  I am going to bring this up at the meeting today.

I propose that we emulate what a desktop editor would do: aggressively save to a temporary file that can be recovered, and have a setting for an auto save interval to disk.  "Checkpointing" should be done using version control.  We should also periodically check for a file change on disk and ask to revert.

**Comment by minrk** [comment]
The [current behavior](https://github.com/ipython/ipython/pull/3158), modeled on modern applications and the norm for web applications, was picked specifically as opposed to the behavior of apps like word and emacs, which necessitates unpleasant things like recovery dialogs, timestamp comparisons etc., the triggers for which are all much more likely to happen in a browser app than a regular desktop application.

With server-side document state, I don't think we would need necessarily need autosave anymore, because the browser is no longer the sole home for unsaved state.

**Comment by blink1073** [comment]
Message received :).  I'll follow the IPEP.

**Comment by Carreau** [comment]
Note that the IPEP apply to the notebook only, but I think consistency is important. I thought agree that is is less than optimal, and agree that a server-side state would be much better.

**Comment by Carreau** [comment]
Bumping that please, I again lost 30 min of work because of a new "go to previous page" chrome shortcut [Ctrl+LeftArrow]

**Comment by blink1073** [comment]
Yep, this is first on my list when I get back.  Also note you can disable that behavior on OSX at least.
