### ISSUE TITLE
Odd rendering bug for checkboxes in widgets

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyterlab#370]
Picture is pretty clear, the "False" case is wrapping:

![image](https://cloud.githubusercontent.com/assets/57394/16831534/56f9efca-495a-11e6-9f55-837e05242563.png)

Snippet for convenient copy/paste testing:

```python
from ipywidgets import interact
interact(lambda x:x, x=False);
```

**Comment by fperez** [comment]
For reference, this is what it looks like in the classic nb:

![Uploading image.png…]()

**Comment by jasongrout** [comment]
I see you closed this. Just checking, right now we have the output rendering correctly, but the checkbox is to the right of the label, instead of the left. This is to be consistent with other controls that have the label on the left, control on the right. Is that all right with you?
<img width="419" alt="screen shot 2016-07-19 at 5 42 44 pm" src="https://cloud.githubusercontent.com/assets/192614/16967673/3748c64c-4dd8-11e6-8598-0c59cef3aebf.png">

**Comment by jasongrout** [comment]
CC @fperez...

**Comment by fperez** [comment]
I think that's ok, and it makes sense to be consistent left/right across widgets. TBH I'd never really paid attention to this inconsistency before, but now that I see it, I agree it's better to clean it up. So no objection from me here.
