### ISSUE TITLE
No typeahead in the console

### ISSUE THREAD

**Issue by asmeurer** [jupyter/jupyterlab#392]
There is no typeahead in the console. 

![jupyterlab](https://cloud.githubusercontent.com/assets/71486/16859038/3d7f04e4-49f1-11e6-9dcf-0b3bde958ebf.gif)

**Comment by blink1073** [comment]
Thanks for the report, @asmeurer.  @afshin, do you want to take this one?

**Comment by afshin** [comment]
@asmeurer could you please explain what you mean by typeahead? Both the console and the notebook have a tab completion facility that works based on users hitting the tab key.

Here is a demonstration. Each time you see a word fill in, it's because I hit the tab key and there was only one available choice. If there is more than one available choice, the tab key will invoke a menu.

![completion](https://cloud.githubusercontent.com/assets/159529/16879544/a61dda86-4a76-11e6-9d12-9076f8febc55.gif)

**Comment by asmeurer** [comment]
See my video. When a command is executing, I should be able to start typing the next command.  This is unrelated to tab completion.

**Comment by afshin** [comment]
@asmeurer thanks, I totally misunderstood your point. I get it now.
