### ISSUE TITLE
jupyterlab does not work with nb_conda_kernels

### ISSUE THREAD

**Issue by cel4** [jupyter/jupyterlab#417]
The current version 0.1.1 of jupyterlab does not like Continuum's `nb_conda_kernels` package. After installing `nb_conda_kernels` I get following error:

```
bundle.js:19335 Uncaught (in promise) Error: Invalid KernelSpecs Model
    at http://localhost:8889/lab/bundle.js:19335:20
```

**Comment by to266** [comment]
The problem seems to be two-fold:

1. the `nb_conda_kernels` do not have a kernel that they specify in the `default` (in my case the default is `python3`, and the kernels they show in the `kernelspec` is `Python [<conda env name>]`.

2. (no clue where in the code this happens, as I'm new..) the jupyterlab does not look for this error, and so does not display anything on the browser after the uncaught error

**Comment by blink1073** [comment]
We have addressed part 2 in the latest master as far as we are away, can either of you confirm?

**Comment by to266** [comment]
Does not seem to work for me, however I'm not sure if I update it properly.

Just get on the branch of interest and `npm install`? (assuming it's `pip -e` installed)

**Comment by blink1073** [comment]
Please run `git pull https://github.com/jupyter/notebook master` (or substitute the name of your upstream remote tracking branch if you have one), then  run `pip install -e .` again.

**Comment by to266** [comment]
you probably meant `jupyterlab` instead of `notebook`...? Anyway, after pip-installing again it works for me.

**Comment by blink1073** [comment]
Yes, sorry, I updated my comment in place ;).  Glad to hear it works!

**Comment by damianavila** [comment]
This is not directly impacting jupyterlab now, but just to let you know, we've released versions of nb_conda, nb_conda_kernels and nb_anacondacloud through the official Anaconda conda repos that should resolve the issues you saw with Python[root].
