### ISSUE TITLE
Navigate to folder outside of home directory

### ISSUE THREAD

**Issue by drussellmrichie** [jupyter/jupyterlab#480]
This is an issue I've long had with Jupyter Notebooks ([and I'm not the only one, apparently?](https://www.reddit.com/r/IPython/comments/3f5ycp/jupyter_321_on_windows_browsing_outside_home/)).

Say I start Jupyter Lab from /Users/russellrichie/jupyterlab. Then within Jupyter Lab, I can't navigate back out of this folder in the 'Files' pallette/pane on the left. I'm stuck looking at /Users/russellrichie/jupyterlab and all its subdirs.

It's not the worst thing in the world -- with a little foresight, I can start jupyter lab from a directory higher up (like /Users/russellrichie), and therefore be able to navigate to all my dirs. But I don't always remember to do this, and anyway, it seems like one should be able to get to *any* directory from within jupyter lab/notebook. What do you all think?

**Comment by jasongrout** [comment]
Thanks for bringing up something that has bothered you.

From my standpoint, it's a design decision to only access to subdirectories in the file browser, and I prefer it that way, rather than granting people permission to browse my entire filesystem. (Granted, they can still access my entire filesystem if the kernel is local, but it's a step in the right direction).

In any case, this would be an issue for the notebook server, not JupyterLab, and in particular the default contents manager provided in the notebook server. Please open the issue at jupyter/notebook to continue discussion, if you'd like.

**Comment by drussellmrichie** [comment]
First, my apologies if I sounded annoyed or bothered, @jasongrout. Jupyter Notebooks (and what I've seen of Lab so far!) are of course awesome. It's just something I've noticed for a while.

Anyway, yes, your explanation makes sense. It's not a huge deal for me, so I'm perfectly fine not to contest the decision. =)

**Comment by jasongrout** [comment]
Thanks. And again, it's really the contents manager that is making these decisions. I think it would be straightforward to make a contents manager you could use that would provide root directory access, if you wanted it.

Alternatively, you could specify a default option to jupyter to always launch with `--notebook-dir=/` or something.
