### ISSUE TITLE
Question about "Inspector"

### ISSUE THREAD

**Issue by svenefftinge** [jupyter/jupyterlab#556]
I saw that something called an inspector was committed yesterday. Could you share what it is or point to some discussion or description. I couldn't find something. Thank you!

**Comment by jasongrout** [comment]
You can see the demo in the Jupyter dev meeting by Darian. https://m.youtube.com/watch?v=dv14RpA0Ht4&feature=youtu.be

**Comment by jasongrout** [comment]
Basically, it provides the tooltip and ?? pager in the sidebar.

**Comment by svenefftinge** [comment]
Ok thank you. It's cool to have a general framework for displaying arbitrary data from the 'active' kernel (or even interacting with it).

Some comments: 
1) I wonder if it wouldn't be better to register a dedicated view (widget) per item rather then putting them all into one widget with an additional tab level. They can be very different and there might be use cases where you want to see two or more of them at the same time.

2) I don't like the idea of showing the result of kernel inspect messages in the inspector, because it is basically static hover information, that we might want to show in any kind of editor at some point. All IDEs I know use a hover widget for this kind of thing.

So it would be really cool, if the inspector was really a framework which I could use to create my own widget and decide where in to dock it and how to render it. The reusable part would be more or less the access to the 'active' kernel.

**Comment by jasongrout** [comment]
CC @afshin

**Comment by jasongrout** [comment]
The inspection machinery is a framework to some extent, as I understand it. @afshin is expecting at least the notebook to use it, if not text files that are hooked up to a kernel. Regardless, I encourage you to dive into the code, if you'd like, and propose a design we can discuss.

**Comment by afshin** [comment]
Hi @svenefftinge, thanks for the comments. The inspector is actually meant to be a general-purpose framework for displaying kernel information. Kernel using widgets, like the notebook and the console can emit `inspected` signals that the `Inspector` picks up. In general, anything that meets the [`Inspector.IInspectable`](https://github.com/jupyter/jupyterlab/blob/e5ea03c3467f2329e0aa5b46edeec0ac308937fa/src/inspector/inspector.ts#L230-L249) interface can be set as the `source` of the inspector.

You could imagine subclassing the `Inspector` class with a behavioral class that does things like hover or overlays if you wanted, but the reason we specifically switched from a hover/tooltip model to a sidebar model is because the tooltips were too obtrusive. Think of the inspector a bit more like the console in a browser combined with the bottom status tray text in Sublime Text that shows you function signatures and hints. You could imagine additional inspector child items including things like code debuggers, *etc.*

But obviously it's brand new and subject to review and critique and change. And we know there will be other extensions that can take the same classes and signals and create a different set of semantics.

The original version that we were considering last week actually had an inspector *per widget*, but one of the core principles of JupyterLab is having lots of activities happening side-by-side and the general consensus we arrived at was that we were giving up way too much real estate if we wanted to attach a code inspector to every single widget, so instead we are treating the inspector as an app-wide resource to be shared.

This set of functionality is going to receive a UX review now that it's in place and can be played with, and that review will almost certainly result in an issue with discussions, so please feel free to chime in there. In addition, if you decide to take a crack at a different interface, I'll be happy to answer any questions that might arise for you. Just try to keep in mind: what will it look like when three notebooks and a console are open and tiled to all be visible?

**Comment by svenefftinge** [comment]
Hi @afshin I generally like the approach and I fully support the "having activities side-by-side" consensus. I just wanted to point out that "details" information is relevant in other context with no access to kernels too. E.g. I want get information about a called method in static code editor, too. 
So my suggestion is to find a UI-pattern that works everywhere rather than having something different for console/notebook and the rest.
Hover seem to work nicely in other IDEs so I wonder what you find obstrusive about that?

**Comment by jasongrout** [comment]
We noticed that the hover was taking a huge amount of space to display the information coming back from the kernel, which was both distracting and covering up lots of the code/ui right at the point of interest (the cursor). Putting the inspector in a dedicated panel was an effort to address that.

**Comment by afshin** [comment]
I don't use a full blown IDE, but I do use plugins that turn my text editor into a hybrid between pure text editing and an IDE, and its approach to showing me method signatures is simply using the bottom tray:

<img width="748" alt="screen shot 2016-07-28 at 12 14 03 pm" src="https://cloud.githubusercontent.com/assets/159529/17210782/d2060dd0-54bc-11e6-99c3-86e37c36ca28.png">

As to your point about static code editing, I would make two points:

1. The "details" tab is actually populated with persistent documentation and has a built-in history. So even if you switch to a non-kernel activity, you can still navigate things you looked up in the past.
2. The data has to come from *somewhere*. So you could imagine a plugin that gives you client-side hints/details for a static code editor or you could imagine hooking up to a kernel just for the introspection capabilities and not executing code ... but somewhere along the line, you'd still need to retrieve that inspected info. So suppose it's a third-party web service and you have loaded a client library in an extension. There's nothing stopping your static text editor from loading that extension and firing its own `inspected` and `clearEphemeral` and `disposed` signals and being a first-class citizen in the application-wide inspector panel.

**Comment by afshin** [comment]
One other thing I would say is that: if there is a broad appetite for a tooltip, one of the things we can offer is supplementing the current `inspected` signal. Currently, the signal emits an `Inspector.IInspectorUpdate`:

```typescript
/**
 * An update value for code inspectors.
 */
export
interface IInspectorUpdate {
  /**
   * The content being sent to the inspector for display.
   */
  content: Widget;

  /**
   * The type of the inspector being updated.
   */
  type: string;
}
```

This only returns a widget with the content that the kernel provided. But we could add to it cursor data like the `coordinates` of the cursor, for example, so that a different `Inspector` implementation could sub-class the current one and use those fields to determine where to render a tooltip.

Our experience currently seems to be that people didn't like the existence of both a completion widget and a tooltip of arbitrarily large size and of fleeting existence (cause it disappears as you type new text in, and you may have still wanted the old text...) on the page.

**Comment by svenefftinge** [comment]
I fully agree that it is useful to have some a help integration for things like '?' in a dedicated widget.
My point is only about information about symbols. I.e. signatures and the first paragraph of documentation or so.

To give another example of how a modern editor (vscode) does this. (Note how they show completion below and context information above the line). It works very well and can easily be removed by pressing escape.

![hovers_and_completions](https://cloud.githubusercontent.com/assets/372735/17213474/b381535c-54d4-11e6-904d-07f62b1e639d.gif)

**Comment by afshin** [comment]
Well, there are two issues:

1. In the console, you are almost always at the *bottom* of the screen because that is where the prompt is, so the space above your code is the only real estate you have for *both* autocompletion and tooltips. This is problematic.
2. Even the *short* version of the inspection response from the kernel (for Python, anyway) is gigantic. I wouldn't want the client side deciding where to truncate that text.

I'm totally sympathetic to where you're coming from and in fact we had tooltips for the past two months ... it just generated complaints. But there's always room for improvement and third party extensions or settings on a per-user basis, *etc.*

**Comment by svenefftinge** [comment]
For the first problem issue #488 seems appropriate. It theoretically is also a problem with editors, but of course more common with a console.

It's ok for me to close this ticket.
