### ISSUE TITLE
Locally build jupyter lab fails to load STIX files

### ISSUE THREAD

**Issue by dhuebner** [jupyter/jupyterlab#590]
I've build jupyter lab locally from master like described in the readme.

After starting and opening an .md file with "Open with -> Rendered Markdown" I noticed a 404 error in the console for the following URL:  
http://localhost:8888/static/components/MathJax/jax/output/HTML-CSS/fonts/STIX/fontdata.js?rev=2.6.0 

On my conda installation the files are in:
~/miniconda3/lib/python3.5/site-packages/notebook/static/components/MathJax/jax/output/HTML-CSS/fonts/__STIX-Web__/ 
.. and not  in
~/miniconda3/lib/python3.5/site-packages/notebook/static/components/MathJax/jax/output/HTML-CSS/fonts/__STIX__/ 

Am I missing some extra dependencies or is that just a bug in jupyter?

**Comment by blink1073** [comment]
Hi @dhuebner, sorry it has taken so long to get back to you.  What is the output of `jupyter notebook --version`?

**Comment by dhuebner** [comment]
@blink1073 HI, it's:

```
bash-3.2$ jupyter notebook --version
4.2.1
```

**Comment by blink1073** [comment]
Ahh, I see what the problem is.  The *published* version of `jupyter/notebook` only includes the `STIX-Web` files, but for some reason we are requesting the `STIX` font explicitly.  I did not notice because I am using the development install of Jupyter Notebook, which has all of the fonts. 

@jasongrout, any ideas on this one?

**Comment by jasongrout** [comment]
huh. I'll look into it.
