### ISSUE TITLE
Unable to execute first cell

### ISSUE THREAD

**Issue by aggFTW** [jupyter/jupyterlab#652]
Hi,

We're trying to use JupyterLab to connect to an existing jupyter server. We see that the first cell doesn't execute, but if we add a new cell, that does execute. Upon looking at some of the objects in the Javascript console, we see that the model for the first cell has its `isDisposed` method returning True. The error manifests itself in the console as:
```
TypeError: write is not a function(…)
at MetadataCursor.setValue (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:11809:10)
    at CodeCellWidget.set [as trusted] (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:17130:34)
    at CodeCellWidget.execute (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:17316:23)
    at Object.runCell (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:2862:35)
    at run (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:2353:36)
    at Object.runAndAdvance (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:2385:17)
    at runAdvanceHandler (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:197:45)
    at safeInvoke (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:56559:26)
    at KeymapManager.processKeydownEvent (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:56348:14)
    at HTMLDocument.<anonymous> (http://localhost:34567/node_modules/jupyterlab/bundle.js?v=local:124:25)safeInvoke @ bundle.js?  v=local:56562KeymapManager.processKeydownEvent @ bundle.js?v=local:56348(anonymous function) @ bundle.js?v=local:124
```

We see that the metadatacursor for the cell has _read and write as null:
```
MetadataCursor {_name: "trusted", _read: null, _write: null}
_name: "trusted"
_read: null
_write: null
name: "trusted"
```

The CodeCellModel for that first cell is disposed of even before the websocket connection is made, but it's never replaced with a new CodeCellModel, so during `CodeCellWidget.prototype.execute`,  when doing `this.trusted = true;` the setter throws that `write is not a function`. I see that the model is being disposed of during the `NotebookModel.prototype._onCellsChanged` started by the `NotebookModel.prototype.fromJSON` function. I also see that a new cell (and CodeCellModel) is added to the NotebookModel during the `fromJSON` function when there's no cells, and that this new model is not disposed...

So I guess my question is why the first cell is still using the old CodeCellModel that was already disposed of?

Thanks!

cc. @afshin

**Comment by blink1073** [comment]
Hi @aggFTW, Darian is off for the next week, but I'll take a look at this on Monday morning.

**Comment by blink1073** [comment]
Hi @aggFTW, I am unable to reproduce, and I can't see where in our signal handling chain this would happen.  Can you describe the exact steps you used to launch Lab page and the notebook document?

Here's what I tried:

- `$ jupyter notebook`
- Navigate to `/lab`
- Open an existing notebook and run first cell
- Create a new notebook and run first cell

**Comment by aggFTW** [comment]
Thanks for taking a look @blink1073! What we are doing is taking the Notebook code in the examples folder and modifying it to point it towards a different `baseURL` for a notebook server that's already running on the machine.

Let me know if you cannot repro and I'll see if I can package something together.

**Comment by blink1073** [comment]
I can't repro:

I ran this in one terminal: `python -m notebook --no-browser --debug --NotebookApp.allow_origin="http://localhost:8765"`

And ran `python main.py` with these modifications:


```diff
diff --git a/examples/lab/main.py b/examples/lab/main.py
index 44da700..2105510 100644
--- a/examples/lab/main.py
+++ b/examples/lab/main.py
@@ -65,8 +65,10 @@ def main(argv):

     thread = threading.Thread(target=print_thread)
     thread.setDaemon(True)
-    thread.start()
+    #thread.start()

+    base_url = 'http://localhost:8888'
+    ws_url = 'ws://localhost:8888'
     handlers = [
         (r"/", MainPageHandler, {'base_url': base_url, 'ws_url': ws_url}),
         (r'/lab/(.*)', tornado.web.StaticFileHandler, {'path': 'build/'}),
```

**Comment by aggFTW** [comment]
Hmmm... working on a repro. Thanks!

**Comment by aggFTW** [comment]
Hi @blink1073:

The key to reproing this is to load a notebook file without any cells. Nothing to do with an external host. Simply replace the contents of `examples\notebook\test.ipynb` file with this:

```
{
 "cells": [],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
```

Thanks!

**Comment by blink1073** [comment]
Thanks @aggFTW, I'll take a look at this on Monday.

**Comment by aggFTW** [comment]
@blink1073 Thanks!

I've been trying to understand the bug today but I'm getting tangled up in signals/emitters :smile: 

From what I see, the `NotebookModel.fromJSON` assigns an empty list of cells, as expected, which invokes the `NotebookModel._onCellsChanged` function. This function adds a new code cell https://github.com/jupyter/jupyterlab/blob/a490e676e2981b0e3d2dbdb0f409b8053d02d2b6/src/notebook/notebook/model.ts#L435

This `cells.add` goes into the `ObservableList.addItem` function, which emits a signal. One of the signal invocations ends up in `StaticNotebook._onCellsChanged` that invokes the `StaticNotebook._insertCell` method with index 0(!) which adds a ``CodeCellWidget` to the list of widgets in layout at index 0. Notice that this list of widgets already has the old disposed cell, which gets bumped to index 1. `activeCellIndex` gets changed to this new index 0.

Afterwards, the original assign call in `fromJSON` invokes the `StaticNotebook._onCellsChanged` function with a replace, and because it was doing a complete replace of all cells, the `args.oldIndex` is 0. However, remember that `Notebook.layout.widgets` now has two cells, the new one being in index 0 and the disposed one in index 1. So, when a `_removeCell` gets called, the wrong cell is removed from the `NotebookPanelLayout`.

Thus, when the first cell gets executed (activeCellIndex == 0), the `CodeCellWidget` that gets picked has had its model disposed and fails to run.

I'm thinking about how to fix it, but I'm not truly sure I understand the differences between `StaticNotebook` and `NotebookModel`... Maybe the easiest solution would be to change `StaticNotebook` to avoid deleting the first cell if `args.newValue` is an empty array... but I think that couple the implementation of `StaticNotebook._onCellsChanged` and `NotebookModel._onCellsChanged`. Any suggestions are welcomed.

This has been a tough one to understand for sure.

Thanks!

**Comment by jasongrout** [comment]
It sounds like the problem is a race condition with the signals, if above is what happens? The `StaticNotebook` should get two signals about the cells changing, first the replace-all-cells-with-no-cells, and then the add-first-cell. However, in your description, it sounds like the add-first-cell invocation is happening before the replace signal invocation.

**Comment by jasongrout** [comment]
Looking more at the code, it seems like what is happening is that:

(1) the cells are replaced by an empty array, which triggers an observable list signal
(2) notebook model picks up this first, sees there is an empty array, and adds a cell. Notice this is changing the list of cells in a cell change handler.
(3) adding a cell reinvokes the cell change handlers, this time with the add
(4) the add cell change handlers all get called, which includes the static notebook `_onCellChanged`: https://github.com/jupyter/jupyterlab/blob/a490e676e2981b0e3d2dbdb0f409b8053d02d2b6/src/notebook/notebook/widget.ts#L327
(5) the stack unwinds to the replace invocation of the notebook model onCellsChanged
(6) the notebook model onCellsChanged completes, letting the static notebook's `_onCellChanged` handler start with the replace invocation.

It sounds like the problem is that a cell is added in the handler for cell changes. Perhaps it would be best to defer adding the cell until after the replace change handlers are *all* called (using something like `setImmediate`).

**Comment by jasongrout** [comment]
Or perhaps instead of setImmediate, the polyfill https://github.com/YuzuJS/setImmediate or maybe in our case https://github.com/kriskowal/asap is better. The idea is to break the nesting by invoking the add cell outside of the replace cells signal handler.

CC @sccolbert - suggestions for this nested signal handler inside another signal handler situation? (see my message above this one)
