### ISSUE TITLE
Deleting cells in a notebook

### ISSUE THREAD

**Issue by AbdealiJK** [jupyter/jupyterlab#773]
After I create a bunch of cells in the jupyterab notebook, I can't seem to be able to figure out how to delete a cell !

I can insert, cut, paste and copy cells using the buttons on the top of the notebook - but nothing to delete cells.
Am I missing something obvious ? Or does this button need to be added ?

This would probably be added in https://github.com/jupyter/jupyterlab/blob/master/src/notebook/notebook/default-toolbar.ts with a new function createDeleteButton I assume.

**Comment by blink1073** [comment]
Hi @AbdealiJK, deleting a cell is available as a palette command, and by default uses the same shortcut as the existing notebook `D, D` (hit `D` twice).  We removed some of the cells from the toolbar to conserve horizontal space since notebooks are going to be viewed alongside other documents in JupyterLab.

**Comment by jasongrout** [comment]
Thanks for asking, and please let us know if you have more questions!
