### ISSUE TITLE
Shift+Tab doesn't show available parameters

### ISSUE THREAD

**Issue by rudolphyo** [jupyter/jupyterlab#867]
Hello!

I recognized that `Shift + Tab` shortcut behaves in different way comparing to jupyter notebook: it doesn`t show you available arguments of function. Instead, it deletes  one tab space before a piece of code on current line.

I would be fascinated with opportunity to have a chance to fix it, but i have no idea where to look. It would be great if someone could give me a piece of advice.

Correct me if I am missing something. 

Thank you!

**Comment by SnoopJeDi** [comment]
I took a look, and it seems like this might be intentional as part of a reorganization of how plugins work in the new version.  If you open a classic notebook interface in JupyterLab, it still has this behavior, provided by [tooltip.js](https://github.com/jupyter/notebook/blob/f75e591bd68d4a6d201a0883a5c3a60694055313/notebook/static/notebook/js/tooltip.js).  That'd be the place to start looking if you wanted to see how this could be integrated into JupyterLab.  This `shift-tab` behavior is established in [src/notebook/codemirror/cells/widget.ts](https://github.com/jupyter/jupyterlab/blob/849efb068d09b059b8c9150f355051b161979292/src/notebook/codemirror/cells/widget.ts#L84), I think.

If you open the inspector on the right-hand side of the Lab interface, it will show the same inspection data as you type a name.  Perhaps `shift-tab` could serve as a keyboard shortcut for grabbing the current word in the inspector and popping the inspector panel out if it's not currently?

**Comment by blink1073** [comment]
This is one area where we explicitly differ from the classic notebook, because shift+tab is generally used in text editors to de-indent text.  Once we have a shortcut editor, this can be configured by the user.

**Comment by jasongrout** [comment]
We'll be introducing a keyboard shortcut editor in the (hopefully near?) future that will let you decide what keyboard shortcuts should do what. Closing this in favor of a shortcut editor #893.
